name: Take Screenshot with Puppeteer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer script
        run: npm run screenshot

      - name: Upload screenshot
        uses: actions/upload-artifact@v3
        with:
          name: example-screenshot
          path: example.png
